# Notebook Dedicated to Study Electron Simulation Observables

In [13]:
import uproot
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

# Load the Data

In [24]:
fdir = '/home/joankl/data/solars/mc/2p2PPO/electrons/ratds/e_2.5MeV_0.root'
data = uproot.open(fdir)
data = data['T;1']
data = data['ds/evs/evs.nhits']
np.array(data)

array([array([830], dtype=uint32), array([764], dtype=uint32),
       array([762], dtype=uint32), array([843], dtype=uint32),
       array([895], dtype=uint32), array([821], dtype=uint32),
       array([617], dtype=uint32), array([803], dtype=uint32),
       array([838], dtype=uint32), array([768], dtype=uint32),
       array([703], dtype=uint32), array([770], dtype=uint32),
       array([824], dtype=uint32), array([707], dtype=uint32),
       array([623], dtype=uint32), array([576], dtype=uint32),
       array([574], dtype=uint32), array([827], dtype=uint32),
       array([780], dtype=uint32), array([823], dtype=uint32),
       array([862], dtype=uint32), array([651], dtype=uint32),
       array([604], dtype=uint32), array([836], dtype=uint32),
       array([737], dtype=uint32), array([720], dtype=uint32),
       array([805], dtype=uint32), array([744], dtype=uint32),
       array([843], dtype=uint32), array([782], dtype=uint32),
       array([815], dtype=uint32), array([677], dtype=u

In [18]:
fdir = '/home/joankl/data/solars/mc/2p2PPO/electrons/npz_files/e_2.5MeV_0.npz'

data = np.load(fdir)
list(data.keys())

['pmt_db',
 'evtid',
 'mcid',
 'energy_mc',
 'energy_recon',
 'pos_mc',
 'pos_recon',
 'dir_mc',
 'sun_dir',
 'hit_pmt_id',
 'hit_time',
 'time_residual_mc',
 'time_residual_recons',
 'hit_qhs',
 'hit_qhl',
 'hit_type',
 'dir_angle_true_recons',
 'dir_angle_true_mc',
 'dir_angle_sun']

In [20]:
var = data['sun_dir']
var

array([], dtype=float64)